plugins {
    id 'java'
}

group = 'org.choongang'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-webmvc:6.1.10'

    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.1.1'

    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:3.0.1'

    implementation 'org.apache.tomcat:tomcat-jdbc:10.1.25'
    implementation 'org.springframework:spring-jdbc:6.1.10'
    implementation 'org.springframework.data:spring-data-jdbc:3.3.1'

    implementation 'org.mybatis:mybatis:3.5.16'
    implementation 'org.mybatis:mybatis-spring:3.0.3'
    implementation 'com.oracle.database.jdbc:ojdbc11:23.4.0.24.05'

    compileOnly 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'

    implementation 'org.slf4j:slf4j-api:2.0.13'
    testImplementation 'ch.qos.logback:logback-classic:1.5.6'

    testImplementation 'org.springframework:spring-test:6.1.10'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}