spring:
  # 데이터베이스 설정
  datasource:
    driver-class-name: org.h2.Driver #테스트 db
    url: jdbc:h2:mem:test
    username: sa
    password:

  # JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true # 실행하는 SQL을 콘솔에 출력
        format_sql: true # 실행하는 SQL의 들여쓰기 및 줄 개행
        use_sql_comments: true
        #dialect: org.hibernate.dialect.OracleDialect

    hibernate:
      ddl-auto: create

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type: trace
