spring:
  jpa:
    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: false

  web:
    resources:
      static-locations: classpath:/static/

  thymeleaf:
    cache: true
    prefix: classpath:/templates/

file:
  upload:
    path: /home/ubuntu/uploads
    url: /upload/