server:
  port: 3000

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@${db.host}:${db.port}:XE
    username: ${db.username}
    password: ${db.password}

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: create

  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: file:src/main/resources/static

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
      file-size-threshold: 30MB

file:
  upload:
    path: D:/uploads
    url: /upload/

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
